apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: dev
spec:
  schedule: "0 2 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: postgres:15
            command:
            - /bin/sh
            - -c
            - |
              echo "Starting backup at $(date)"
              pg_dump -h postgres-service -U postgres -d expenses
\
                > /backup/expenses-$(date +%Y%m%d-%H%M%S).sql
              echo "Backup complete: $(ls -lh /backup/)"
            env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: devops-app-secret
                  key: DB_PASSWORD
            volumeMounts:
            - name: backup-vol
              mountPath: /backup
          volumes:
          - name: backup-vol
            persistentVolumeClaim:
              claimName: postgres-backup-pvc
          restartPolicy: OnFailure