apiVersion: v1
kind: Pod
metadata:
  name: nfs-writer
  namespace: dev
spec:
  nodeSelector:
    kubernetes.io/hostname: worker1
  containers:
  - name: writer
    image: busybox
    command: ["/bin/sh", "-c", "while true; do echo $(date) >> /data/test.txt; sleep 5; done"]
    volumeMounts:
    - name: nfs-vol
      mountPath: /data
  volumes:
  - name: nfs-vol
    persistentVolumeClaim:
      claimName: nfs-test-pvc
---
apiVersion: v1
kind: Pod
metadata:
  name: nfs-reader
  namespace: dev
spec:
  nodeSelector:
    kubernetes.io/hostname: worker2
  containers:
  - name: reader
    image: busybox
    command: ["/bin/sh", "-c", "while true; do cat /data/test.txt; sleep 5; done"]
    volumeMounts:
    - name: nfs-vol
      mountPath: /data
  volumes:
  - name: nfs-vol
    persistentVolumeClaim:
      claimName: nfs-test-pvc