apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
  namespace: dev
  labels:
    app: devops-app
    managed-by: argocd

spec:
  replicas: 3

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: devops-app

  template:
    metadata:
      labels:
        app: devops-app
        managed-by: argocd
    spec:
      nodeSelector:
        node-role: app
      containers:
      - name: devops-app
        image: rdcstr30/devops-app:latest
            
        env:
        - name: APP_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: APP_SECRET

        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: devops-app-config
              key: APP_ENV

        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: devops-app-config
              key: LOG_LEVEL

        volumeMounts:
        - name: app-storage
          mountPath: /data

        ports:
        - containerPort: 5000

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"

        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10

      volumes:
      - name: app-storage
        persistentVolumeClaim:
          claimName: devops-app-pvc
