apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-app-config
  namespace: dev
data:
  APP_ENV: "dev"
  LOG_LEVEL: "DEBUG"
  DB_HOST: "postgres-service"
  DB_NAME: "expenses"
  DB_USER: "postgres"