apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: devops-app-secret
  namespace: dev
spec:
  encryptedData:
    DB_PASSWORD: AgB33vwIu1gCof5GVQl16EN+m1firZkQ+SHrqyoLrWDzmtAz3m8+xgROwNvILBly2AUoCzTyvIg8IO7gBZKChgMC2w/jUI6seqmhANs7KMjIU87WtKcWLLXq+b3Cvq0DZBRUNlwvxZtMWKDZ5e3VeWRIWEuJcJGJmQH1h+dOImCi0nsFtCm3MWpwvAKEsboWJraa9XTqrubYvsp/Fu5rYdUIZH9lemOiIkFOAA1UBoZ6DVEJhJolNbobwqHapjCLsEsXIuSt0EWxxYRoT53n9O+v1e42ltDYmSvYsa00oZFqp8fczYliBhVUvwHoM2bnQIOaOsmZx8hoJtAxphL9dTuEgJoV+92KV8K+e2Ir3I8WNgpfae6AE5BpRaoxtoBcedmBHl9tuGEJ2c/+z+W/YGWznJIANHKR/modrvYd5+QDtMlR/7OWEVuJUoBQ0X3bVxcTGmghLTKrOQJEInBJNO5kxtN+Vi1bVYFQLiLu6JFtRQnkzF3BppXRjC3ZkKDi6b8j64J4rQaEPmr1ORO7a5lz6rKm0LgatwFfb9vO68B0HlMcw9qvA8LrGvjojl3R9/DbZshYHWrAS9MAH8GXAOk8z4vS4TDeFEv34+cbaZnlwzRE3etywoyxNGdBKhdHJGGLv294KzDZ9uyArvgKzShBtirsfFmkVxI7aeS88HTSojg6C6Zzcg18DM/BoFkuAWrx5gVcm/uMt59ZI3Y/3g==
  template:
    metadata:
      creationTimestamp: null
      name: devops-app-secret
      namespace: dev