apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-app-sa
  namespace: dev
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-ops-sa
  namespace: dev
