name: Docker CI/CD

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devops-app:latest .

      - name: Push Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy Kubernetes manifest to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_VM2_IP }}
          username: azureuser
          key: ${{ secrets.VM_SSH_KEY }}
          source: "k8s"
          target: "/home/azureuser"

      - name: Deploy to K3s on Azure VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_VM2_IP }}
          username: azureuser
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /home/azureuser
            kubectl apply -f k8s/dev
            kubectl rollout restart deployment/devops-app -n dev
            kubectl rollout status deployment/devops-app -n dev
            kubectl get pods -n dev

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy Kubernetes manifests to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_VM2_IP }}
          username: azureuser
          key: ${{ secrets.VM_SSH_KEY }}
          source: "k8s"
          target: "/home/azureuser"

      - name: Deploy to staging
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_VM2_IP }}
          username: azureuser
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /home/azureuser
            kubectl apply -f k8s/staging/
            kubectl rollout restart deployment/devops-app -n staging
            kubectl rollout status deployment/devops-app -n staging
            kubectl get pods -n staging